name: jenkinsfile-runner-prepackaged with Github Action Context
description: Run jenkinsfile-runner-prepackaged - with credentials
author: inspirit941
branding:
  icon: archive
  color: orange
inputs:
  jenkinsfile:
    description: Jenkinsfile location to test
    default: Jenkinsfile
    required: true
  plugins:
    description: plugins.txt location
    default: plugins.txt
    required: false
  scmfile:
    description: scmfile.txt location
    default: scmfile.yaml
    required: false
  command:
    description: Jenkinsfile-runner command, i.e; run or lint
    default: run
    required: false
  token:
      description: The GitHub token used to create an authenticated client
      default: ${{ github.token }}
      required: false
  username:
      description: The GitHub token used to create an authenticated client
      default: ${{ github.token }}
      required: false
  url:
      description: The GitHub token used to create an authenticated client
      default: ${{ github.token }}
      required: false
  name:
      description: The GitHub token used to create an authenticated client
      default: ${{ github.token }}
      required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.jenkinsfile }}
    - ${{ inputs.plugins }}
    - ${{ inputs.scmfile }}
    - ${{ inputs.command }}
    - ${{ inputs.token }}
    - ${{ inputs.username }}
    - ${{ inputs.url }}
    - ${{ inputs.name }}
